name: CI/CD for FastAPI & Streamlit App

on:
  push:
    branches:
      - main  # Runs on push to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          python -m unittest discover -s tests  # Runs all test cases inside `tests/`

  build-and-push:
    needs: test  # Runs only if tests pass
    runs-on: ubuntu-latest

    steps:
      # Step 5: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and Push Backend Image
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/food_contamination_backend:latest -f backend.Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/food_contamination_backend:latest

      # Step 8: Build and Push Frontend Image
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/food_contamination_frontend:latest -f frontend.Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/food_contamination_frontend:latest

